**Лабораторная работа №1: Pandas**

**Выполнила: Мишагина Валерия 6133**

Датасет -  [2024 TMDB Latest Movie Data  ](https://www.kaggle.com/datasets/hafiznouman786/2024-tmdb-latest-movie-data?resource=download)

In [ ]:
import pandas as pd

**№1.** Считать в `pandas.DataFrame` любой источник данных: CSV, JSON, Excel-файл, HTML-таблицу и т.п.

In [45]:
data = pd.read_csv('movies2.csv')

**№2.** Привести описание датасета.

*Этот набор данных содержит последние данные о фильмах, полученные с веб-сайта TMDB, предоставляя исчерпывающую информацию за 2024 год. Он включает подробную информацию о фильмах, такую как названия, даты выхода, жанры, рейтинги и многое другое. С его помощью можно обучить модели для таких задач, как системы рекомендаций к фильмам, анализ настроений и прогнозы кассовых сборов.*

Описание столбцов датасета [2024 TMDB Latest Movie Data  ](https://www.kaggle.com/datasets/hafiznouman786/2024-tmdb-latest-movie-data?resource=download)

* movie_id: Unique identifier for each movie.
* title: Title of the movie.
* release_date: Release date of the movie.
* genre: Genre(s) of the movie.
* overview: Brief summary or synopsis of the movie.
* popularity: Popularity score of the movie.
* vote_average: Average rating of the movie.
* vote_count: Number of votes the movie has received.

In [46]:
# информация о данных в DataFrame, тип данных признаков
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9400 entries, 0 to 9399
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9400 non-null   int64
 1   original_title  9400 non-null   object
 2   overview        9399 non-null   object
 3   release_date    9400 non-null   object
 4   popularity      9400 non-null   float64
 5   vote_average    9400 non-null   float64
 6   vote_count      9400 non-null   int64
 7   genre_names     9400 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 587.6+ KB

In [47]:
# размерность датасета
data.shape

(9400, 8)

**3.** Выполнить над датафреймом следующие операции:

In [48]:
#.head()
data.head()

,id,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221,"['Drama', 'Crime']"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877,"['Drama', 'Crime']"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001,"['Drama', 'Crime']"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409,"['Drama', 'History', 'War']"
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276,['Drama']

In [49]:
#.describe()
# статистика по числовым признакам
data.describe()

                 id   popularity  vote_average    vote_count
count  9.400000e+03  9400.000000   9400.000000   9400.000000
mean   1.886253e+05    42.855597      6.636562   1971.110319
std    2.501381e+05    90.352175      0.782143   3092.303425
min    2.000000e+00     0.020000      3.270000    300.000000
25%    1.004650e+04    16.841750      6.114750    466.000000
50%    3.665250e+04    24.360500      6.658000    842.000000
75%    3.440978e+05    38.226000      7.200000   1966.000000
max    1.212073e+06  3629.389000      8.705000  35768.000000

Считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки)

In [50]:
data['original_title'][0]

'The Shawshank Redemption'

Фильтрация строк по диапазону индекса

In [51]:
data.loc[3:6, ['popularity', 'vote_average']]

   popularity  vote_average
3      77.039         8.567
4      76.566         8.541
5      33.484         8.537
6     103.963         8.536

In [52]:
data.loc[3:6, :]

,id,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409,"['Drama', 'History', 'War']"
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276,['Drama']
5,19404,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,33.484,8.537,4388,"['Comedy', 'Drama', 'Romance']"
6,129,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,103.963,8.536,15949,"['Animation', 'Family', 'Fantasy']"

Фильтрация набора данных по какому-либо условию

In [53]:
# рейтинг больше 8.5 и кол-во голосов больше 10000
data[(data["vote_average"] > 8.5) & (data["vote_count"] > 10000)]

,id,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221,"['Drama', 'Crime']"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877,"['Drama', 'Crime']"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001,"['Drama', 'Crime']"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409,"['Drama', 'History', 'War']"
6,129,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,103.963,8.536,15949,"['Animation', 'Family', 'Fantasy']"
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,95.154,8.515,31978,"['Drama', 'Action', 'Crime', 'Thriller']"
8,496243,기생충,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,89.722,8.509,17573,"['Comedy', 'Thriller', 'Drama']"

Работа с пропущенными значениями

In [54]:
# для начала проверим, есть ли в датасете пропущенные значения
data.isna().sum()

id                0
original_title    0
overview          1
release_date      0
popularity        0
vote_average      0
vote_count        0
genre_names       0
dtype: int64

Пропущенных значений практически нет, сгенерируем их.

In [55]:
import random
import numpy as np

columns = data.columns
for i in range(100):
    data.loc[random.randint(0, data.shape[0] -1), columns[random.randint(0, data.shape[1] -1)]] = np.nan

In [56]:
data.isna().sum()

id                14
original_title    14
overview          12
release_date      10
popularity        11
vote_average      14
vote_count        12
genre_names       14
dtype: int64

Видим, что появились пропуски. Теперь удалим строки с пропусками в колонках 'genre_names', 'riginal_title', 'id', 'release_date', 'overview'

In [57]:
data = data.dropna(subset=["id", "original_title", "genre_names", "release_date", "overview"])

In [58]:
data.isna().sum()

id                 0
original_title     0
overview           0
release_date       0
popularity        11
vote_average      14
vote_count        12
genre_names        0
dtype: int64

In [59]:
data.shape

(9336, 8)

В числовых колонках заполним пропуски средним значением по столбцу

In [60]:
data[columns[4]] = data[columns[4]].fillna(data[columns[4]].mean())
data[columns[5]] = data[columns[5]].fillna(data[columns[5]].mean())
data[columns[6]] = data[columns[6]].fillna(data[columns[6]].mean().round(0))

In [61]:
data.isna().sum()

id                0
original_title    0
overview          0
release_date      0
popularity        0
vote_average      0
vote_count        0
genre_names       0
dtype: int64

Создание нового поля, вычисленного на основе значений других полей

In [62]:
#через выражение на базе имеющихся колонок
# success = popularity * vote_average
data["success"] = (data["popularity"] * data["vote_average"]).round(3)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9336 entries, 0 to 9399
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9336 non-null   float64
 1   original_title  9336 non-null   object
 2   overview        9336 non-null   object
 3   release_date    9336 non-null   object
 4   popularity      9336 non-null   float64
 5   vote_average    9336 non-null   float64
 6   vote_count      9336 non-null   float64
 7   genre_names     9336 non-null   object
 8   success         9336 non-null   float64
dtypes: float64(5), object(4)
memory usage: 729.4+ KB

In [63]:
# через DataFrame.apply
data["vote_average, %"] = data.apply(lambda row: row["vote_average"] * 10, axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9336 entries, 0 to 9399
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               9336 non-null   float64
 1   original_title   9336 non-null   object
 2   overview         9336 non-null   object
 3   release_date     9336 non-null   object
 4   popularity       9336 non-null   float64
 5   vote_average     9336 non-null   float64
 6   vote_count       9336 non-null   float64
 7   genre_names      9336 non-null   object
 8   success          9336 non-null   float64
 9   vote_average, %  9336 non-null   float64
dtypes: float64(6), object(4)
memory usage: 802.3+ KB

In [64]:
# через DataFrame.apply
data["is_new"] = data["release_date"].apply(lambda e:  e > '2023-01-01')
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9336 entries, 0 to 9399
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               9336 non-null   float64
 1   original_title   9336 non-null   object
 2   overview         9336 non-null   object
 3   release_date     9336 non-null   object
 4   popularity       9336 non-null   float64
 5   vote_average     9336 non-null   float64
 6   vote_count       9336 non-null   float64
 7   genre_names      9336 non-null   object
 8   success          9336 non-null   float64
 9   vote_average, %  9336 non-null   float64
 10  is_new           9336 non-null   bool
dtypes: bool(1), float64(6), object(4)
memory usage: 811.4+ KB

In [65]:
bins = [0, 4, 7, 10]
labels = ['low', 'medium', 'high']
data['rating'] = pd.cut(data['vote_average'], bins=bins, labels=labels)

Сортировка по какому-либо из полей

In [66]:
# сортировка по release_date
data.sort_values("release_date")

,id,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names,success,"vote_average, %",is_new,rating
384,775.0,Le Voyage dans la Lune,Professor Barbenfouillis and five of his colle...,1902-04-17,20.963,7.927,1706.0,"['Adventure', 'Science Fiction']",166.174,79.27,False,high
3157,5698.0,The Great Train Robbery,After the train station clerk is assaulted and...,1903-12-07,11.828,7.008,584.0,"['Crime', 'Action', 'Western', 'Adventure']",82.891,70.08,False,high
7371,618.0,The Birth of a Nation,"Two families, abolitionist Northerners the Sto...",1915-02-08,13.484,6.000,504.0,"['Drama', 'History', 'War']",80.904,60.00,False,medium
2696,3059.0,Intolerance: Love's Struggle Throughout the Ages,"The story of a poor young woman, separated by ...",1916-09-04,12.227,7.120,321.0,"['Drama', 'History']",87.056,71.20,False,high
1839,36208.0,A Dog's Life,The Tramp and his dog companion struggle to su...,1918-04-14,10.943,7.300,310.0,['Comedy'],79.884,73.00,False,high
...,...,...,...,...,...,...,...,...,...,...,...,...
1937,746036.0,The Fall Guy,"Fresh off an almost career-ending accident, st...",2024-04-24,1915.521,7.318,815.0,"['Action', 'Comedy']",14017.783,73.18,True,high
1506,843527.0,The Idea of You,"Solène, a 40-year-old single mom, begins an un...",2024-05-02,392.623,7.428,891.0,"['Romance', 'Comedy', 'Drama']",2916.404,74.28,True,high
2835,653346.0,Kingdom of the Planet of the Apes,Several generations in the future following Ca...,2024-05-08,3629.389,7.100,647.0,"['Science Fiction', 'Adventure', 'Action']",25768.662,71.00,True,high
714,786892.0,Furiosa: A Mad Max Saga,"As the world fell, young Furiosa is snatched f...",2024-05-22,1193.177,7.701,412.0,"['Action', 'Adventure', 'Science Fiction']",9188.656,77.01,True,high
4430,614933.0,Atlas,A brilliant counterterrorism analyst with a de...,2024-05-23,820.285,6.723,368.0,"['Science Fiction', 'Action']",5514.776,67.23,True,medium

Вычисление нескольких статистик по колонкам (использовать встроенные агрегатные функции - любые на выбор)

In [67]:
print(f"Mean vote_average: {data['vote_average'].mean()}")
print(f"Max release_date: {data['release_date'].max()}")
print(f"Min popularity: {data['popularity'].min()}")
print(f"Sum vote_count: {data['vote_count'].sum()}")

Mean vote_average: 6.6365673675177
Max release_date: 2024-05-23
Min popularity: 0.02
Sum vote_count: 18408055.0

Вывод по какому-либо полю / набору полей числа значений с использованием `.value_counts()`.

In [68]:
data["genre_names"].value_counts()

genre_names
['Comedy']                                                  553
['Drama']                                                   536
['Comedy', 'Romance']                                       248
['Drama', 'Romance']                                        246
['Comedy', 'Drama']                                         217
                                                           ...
['Fantasy', 'Animation', 'Romance', 'Family']                 1
['Romance', 'Comedy', 'Crime', 'Fantasy']                     1
['Animation', 'Family', 'TV Movie', 'Comedy', 'Fantasy']      1
['Adventure', 'Horror']                                       1
['Fantasy', 'Science Fiction', 'Family', 'TV Movie']          1
Name: count, Length: 2026, dtype: int64

In [70]:
data["is_new"].value_counts()

is_new
False    9096
True      240
Name: count, dtype: int64

Вывод уникальных значений какой-либо колонки с использованием `.unique()`

In [71]:
data["genre_names"].unique()

array(["['Drama', 'Crime']", "['Drama', 'History', 'War']", "['Drama']",
       ..., "['Adventure', 'Thriller', 'Horror']",
       "['Horror', 'Comedy', 'Science Fiction', 'Action', 'TV Movie']",
       "['Fantasy', 'Science Fiction', 'Family', 'TV Movie']"],
      dtype=object)

Удаление текущего индекса, и создание нового индекса на базе новой колонки, которая для этого лучше всего подходит

In [72]:
data

,id,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names,success,"vote_average, %",is_new,rating
0,278.0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221.0,"['Drama', 'Crime']",1010.111,87.05,False,high
1,238.0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877.0,"['Drama', 'Crime']",1459.317,86.95,False,high
2,240.0,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001.0,"['Drama', 'Crime']",1414.251,85.76,False,high
3,424.0,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409.0,"['Drama', 'History', 'War']",659.993,85.67,False,high
4,389.0,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276.0,['Drama'],653.950,85.41,False,high
...,...,...,...,...,...,...,...,...,...,...,...,...
9395,9544.0,FearDotCom,When four bodies are discovered among the indu...,2002-08-09,14.975,3.724,346.0,"['Horror', 'Thriller', 'Crime']",55.767,37.24,False,low
9396,485774.0,The Open House,A teenager and his mother find themselves besi...,2018-01-19,14.647,3.701,1317.0,"['Horror', 'Thriller']",54.209,37.01,False,low
9397,10870.0,Les Dalton,Joe and Averell are the eldest and youngest of...,2004-11-08,21.351,3.681,329.0,"['Comedy', 'Western', 'Adventure']",78.593,36.81,False,low
9398,74849.0,The Star Wars Holiday Special,Luke Skywalker and Han Solo battle evil Imperi...,1978-11-17,11.516,3.300,441.0,"['Fantasy', 'Science Fiction', 'Family', 'TV M...",38.003,33.00,False,low
9399,5491.0,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,22.800,3.270,814.0,"['Science Fiction', 'Action', 'Adventure']",74.556,32.70,False,low

In [73]:
data = data.reset_index(drop=True)
data = data.set_index("id")
data

,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names,success,"vote_average, %",is_new,rating
id,,,,,,,,,,,
278.0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221.0,"['Drama', 'Crime']",1010.111,87.05,False,high
238.0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877.0,"['Drama', 'Crime']",1459.317,86.95,False,high
240.0,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001.0,"['Drama', 'Crime']",1414.251,85.76,False,high
424.0,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409.0,"['Drama', 'History', 'War']",659.993,85.67,False,high
389.0,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276.0,['Drama'],653.950,85.41,False,high
...,...,...,...,...,...,...,...,...,...,...,...
9544.0,FearDotCom,When four bodies are discovered among the indu...,2002-08-09,14.975,3.724,346.0,"['Horror', 'Thriller', 'Crime']",55.767,37.24,False,low
485774.0,The Open House,A teenager and his mother find themselves besi...,2018-01-19,14.647,3.701,1317.0,"['Horror', 'Thriller']",54.209,37.01,False,low
10870.0,Les Dalton,Joe and Averell are the eldest and youngest of...,2004-11-08,21.351,3.681,329.0,"['Comedy', 'Western', 'Adventure']",78.593,36.81,False,low
74849.0,The Star Wars Holiday Special,Luke Skywalker and Han Solo battle evil Imperi...,1978-11-17,11.516,3.300,441.0,"['Fantasy', 'Science Fiction', 'Family', 'TV M...",38.003,33.00,False,low
5491.0,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,22.800,3.270,814.0,"['Science Fiction', 'Action', 'Adventure']",74.556,32.70,False,low

**4.** Продемонстрировать работу `.groupby`, на основе группировок в `groupby` вычислить агрегатные функции по одной или нескольким колонкам

In [74]:
data_group = data.groupby("rating")
data_group["popularity"].mean()

rating
low       20.633308
medium    35.661867
high      57.471052
Name: popularity, dtype: float64

In [75]:
data_group["vote_count"].min()

rating
low       329.0
medium    300.0
high      300.0
Name: vote_count, dtype: float64

In [76]:
data_group["vote_count"].max()

rating
low        1530.0
medium    21705.0
high      35768.0
Name: vote_count, dtype: float64

**№5.** Решейпинг данных с использованием .pivot (можно подать на вход результаты агрегатов, полученных ранее с использованием .groupby (сгруппировать по двум полям).

In [79]:
# группировка по признау "новизны" фильма и по рейтингу. подсчет средней "порулярности" по группе
grouped = data.groupby(['is_new', 'rating'], as_index=False)['popularity'].mean()
grouped

   is_new  rating  popularity
0   False     low   20.633308
1   False  medium   34.210076
2   False    high   49.322902
3    True     low         NaN
4    True  medium  101.382522
5    True    high  289.385858

In [81]:
grouped.pivot(columns='rating', index='is_new', values='popularity')

rating        low      medium        high
is_new
False   20.633308   34.210076   49.322902
True          NaN  101.382522  289.385858

**№6.** Решейпинг данных, соединённых с группировкой / агрегацией (одним словом - сводная таблица): .pivot_table. Группировать только по категориальным полям или числовым, если значений немного.

In [93]:
# загрубим значение даты выхода для группировке по годам
data['release_year'] = data["release_date"].apply(lambda e:  str(round(int(e[0:4]), -1)) + '-e')

In [94]:
data.pivot_table(values='popularity', index='release_year', columns='rating', aggfunc='mean')

rating              low     medium       high
release_year
1900-e              NaN        NaN  16.395500
1920-e              NaN  13.484000  18.775700
1930-e              NaN  14.214333  48.684000
1940-e              NaN  21.961375  40.805322
1950-e              NaN  17.243067  32.230684
1960-e              NaN  24.537655  27.276216
1970-e              NaN  30.889070  32.906915
1980-e        11.516000  35.747231  63.928538
1990-e        24.920000  32.151408  54.073453
2000-e        22.047200  31.346005  48.599844
2010-e        20.185333  28.380060  41.466220
2020-e        20.335000  47.057916  84.611927

**№7.** Вычислить квантили распределения какого-либо вещественного признака

In [95]:
print(np.quantile(data['popularity'], 0.25))
print(np.quantile(data['popularity'], 0.75))

16.847749999999998
38.25975

**№8.** Вычислить (в виде текста) гистограмму какого-либо вещественного признака

In [97]:
#гистограмма средней оценки фильма
np.histogram(data['vote_average'])

(array([   6,   46,  141,  417, 1218, 2297, 2336, 1944,  782,  149]),
 array([3.27  , 3.8135, 4.357 , 4.9005, 5.444 , 5.9875, 6.531 , 7.0745,
        7.618 , 8.1615, 8.705 ]))

**№9.** Проитерировать `DataFrame` построчно `.iterrows()` и выполнить какую-либо операцию внутри цикла.

In [123]:
# в цикле найдем и выведем названия фильмов 20-х годов с рейтингом больше 8.3
for _, row in data.iterrows():
  if ((row['release_year'] == '2020-e') & (row['vote_average'] > 8.3)):
    print(row['original_title'])

기생충
君の名は。
Radical
Cosas imposibles
同級生
Gabriel's Inferno
Primal: Tales of Savagery
Spider-Man: Into the Spider-Verse
Gabriel's Inferno: Part II
罗小黑战记
Gabriel's Inferno: Part III
Taylor Swift: Reputation Stadium Tour
TAYLOR SWIFT | THE ERAS TOUR
映画 聲の形
Spider-Man: Across the Spider-Verse
映画 五等分の花嫁
Once Upon a Studio
Dedicada A Mi Ex

**№10.** Получить `DataFrame` с `MultiIndex` любым способом:

Загрубим значения датасета. Выделим среди жанров фильма "главный"

In [145]:
data = data[data['genre_names'] != '[]']
data['main_genre'] = data["genre_names"].apply(lambda e: e.split('\'')[1])

In [151]:
data_multi = data.pivot_table(index = ['release_year', 'rating'], columns = 'main_genre', values = 'vote_count').fillna(0).astype(int)
data_multi

main_genre           Action  Adventure  Animation  Comedy  Crime  Drama  \
release_year rating
1900-e       high         0       1706          0       0    584      0
1920-e       medium       0          0          0       0      0    504
             high       936       1529          0     929      0    814
1930-e       medium       0          0          0       0      0      0
             high         0       1410        513     878    448   1386
1940-e       medium       0          0        553     353    344    312
             high         0       1716       4717     951    674   1132
1950-e       medium       0        577        452     500      0    515
             high      3505        987       5440     889    889    860
1960-e       medium     559       1395          0     501    314    499
             high      1427       2615       1629    1144    966    860
1970-e       medium     890       1222        307     579    516    513
             high      1051        918       2727     759   1145   1520
1980-e       low          0          0          0       0      0      0
             medium     766       1125        779     635    544    775
             high      2869       6396        638    1600   2454   1655
1990-e       low          0          0          0       0      0      0
             medium    1052       1432        645     973    849    727
             high      3059       5067       2340    2299   3214   2181
2000-e       low        459          0          0     329      0      0
             medium    1853       2493       1315    1272   1065    925
             high      5886       8399       4083    2582   3045   2675
2010-e       low          0          0          0     955      0      0
             medium    2986       2839       2201    1349   1452   1166
             high      6634       8194       2984    3145   4339   3009
2020-e       low          0          0          0     446      0      0
             medium    2437       3296       1159     986   1441   1014
             high      5525       4825       1984    2446   3190   1985

main_genre           Family  Fantasy  History  Horror  Music  Mystery  \
release_year rating
1900-e       high         0        0        0       0      0        0
1920-e       medium       0        0        0       0      0        0
             high         0        0        0    1895      0        0
1930-e       medium       0        0        0     583    375        0
             high         0      326        0     912      0        0
1940-e       medium       0        0        0       0      0      554
             high         0     7143        0     729      0     1642
1950-e       medium       0        0        0     437      0        0
             high      6494      542        0       0    549      798
1960-e       medium       0     4975        0     447    652      301
             high      5093     2852     2357    1621   1243     2810
1970-e       medium     580      419        0     516    435      394
             high      3283      400     1045    2589    646      381
1980-e       low          0      441        0       0      0        0
             medium     518      948        0     802   1842      593
             high       953     2121     2694    4413   1569      466
1990-e       low          0        0        0     407      0        0
             medium     916      890        0     872   1720      421
             high      5048     4724        0    2965   1143      549
2000-e       low          0        0        0     346      0        0
             medium    1814     2145      492    1496    684     1311
             high      2364     5549      382    4093      0     4216
2010-e       low          0        0        0    1530      0        0
             medium    1439     2906     1297    1474   1044      971
             high      3266     6431     5351    3979   1546    10282
2020-e       low          0        0        0    1026      0        0
             medium    1966     2386      936    1415    406     1762
             high      2454     3530     1390    4523   2608     3793

main_genre           Romance  Science Fiction  TV Movie  Thriller   War  \
release_year rating
1900-e       high          0                0         0         0     0
1920-e       medium        0                0         0         0     0
             high          0                0         0         0     0
1930-e       medium        0                0         0       373     0
             high        405                0         0         0     0
1940-e       medium        0                0         0       419     0
             high          0                0         0       653   410
1950-e       medium        0              495         0       335     0
             high        768             1063         0      2292   600
1960-e       medium        0              516         0       515     0
             high        520              791         0       763  1185
1970-e       medium      524              634         0       517   313
             high        469             6911         0       478   630
1980-e       low           0                0         0         0     0
             medium      802              962         0       658   564
             high       7010             4932         0      1081   458
1990-e       low           0                0         0         0     0
             medium     1413             1346       312       795   711
             high       4558             4015         0      7321   351
2000-e       low           0              606         0         0     0
             medium     1019             1803       341      1304  2161
             high       4105             5639         0      5210   667
2010-e       low           0                0         0         0     0
             medium     1085             3207       599      1531  1775
             high       3230             5899       485      3421  7884
2020-e       low           0                0         0         0     0
             medium      997             2064       430      1060  1020
             high       1970             4735       603      2335  2253

main_genre           Western
release_year rating
1900-e       high          0
1920-e       medium        0
             high          0
1930-e       medium        0
             high          0
1940-e       medium        0
             high        708
1950-e       medium      322
             high        557
1960-e       medium      338
             high       1721
1970-e       medium      534
             high       1618
1980-e       low           0
             medium      681
             high        807
1990-e       low           0
             medium      633
             high       3122
2000-e       low           0
             medium     1044
             high       1007
2010-e       low           0
             medium      651
             high       3450
2020-e       low           0
             medium      990
             high       8624

Переставить местами уровни индекса

In [147]:
data_multi.swaplevel().sort_index()

main_genre           Action  Adventure  Animation  Comedy  Crime  Drama  \
rating release_year
low    1980-e             0          0          0       0      0      0
       1990-e             0          0          0       0      0      0
       2000-e           459          0          0     329      0      0
       2010-e             0          0          0     955      0      0
       2020-e             0          0          0     446      0      0
medium 1920-e             0          0          0       0      0    504
       1930-e             0          0          0       0      0      0
       1940-e             0          0        553     353    344    312
       1950-e             0        577        452     500      0    515
       1960-e           559       1395          0     501    314    499
       1970-e           890       1222        307     579    516    513
       1980-e           766       1125        779     635    544    775
       1990-e          1052       1432        645     973    849    727
       2000-e          1853       2493       1315    1272   1065    925
       2010-e          2986       2839       2201    1349   1452   1166
       2020-e          2437       3296       1159     986   1441   1014
high   1900-e             0       1706          0       0    584      0
       1920-e           936       1529          0     929      0    814
       1930-e             0       1410        513     878    448   1386
       1940-e             0       1716       4717     951    674   1132
       1950-e          3505        987       5440     889    889    860
       1960-e          1427       2615       1629    1144    966    860
       1970-e          1051        918       2727     759   1145   1520
       1980-e          2869       6396        638    1600   2454   1655
       1990-e          3059       5067       2340    2299   3214   2181
       2000-e          5886       8399       4083    2582   3045   2675
       2010-e          6634       8194       2984    3145   4339   3009
       2020-e          5525       4825       1984    2446   3190   1985

main_genre           Family  Fantasy  History  Horror  Music  Mystery  \
rating release_year
low    1980-e             0      441        0       0      0        0
       1990-e             0        0        0     407      0        0
       2000-e             0        0        0     346      0        0
       2010-e             0        0        0    1530      0        0
       2020-e             0        0        0    1026      0        0
medium 1920-e             0        0        0       0      0        0
       1930-e             0        0        0     583    375        0
       1940-e             0        0        0       0      0      554
       1950-e             0        0        0     437      0        0
       1960-e             0     4975        0     447    652      301
       1970-e           580      419        0     516    435      394
       1980-e           518      948        0     802   1842      593
       1990-e           916      890        0     872   1720      421
       2000-e          1814     2145      492    1496    684     1311
       2010-e          1439     2906     1297    1474   1044      971
       2020-e          1966     2386      936    1415    406     1762
high   1900-e             0        0        0       0      0        0
       1920-e             0        0        0    1895      0        0
       1930-e             0      326        0     912      0        0
       1940-e             0     7143        0     729      0     1642
       1950-e          6494      542        0       0    549      798
       1960-e          5093     2852     2357    1621   1243     2810
       1970-e          3283      400     1045    2589    646      381
       1980-e           953     2121     2694    4413   1569      466
       1990-e          5048     4724        0    2965   1143      549
       2000-e          2364     5549      382    4093      0     4216
       2010-e          3266     6431     5351    3979   1546    10282
       2020-e          2454     3530     1390    4523   2608     3793

main_genre           Romance  Science Fiction  TV Movie  Thriller   War  \
rating release_year
low    1980-e              0                0         0         0     0
       1990-e              0                0         0         0     0
       2000-e              0              606         0         0     0
       2010-e              0                0         0         0     0
       2020-e              0                0         0         0     0
medium 1920-e              0                0         0         0     0
       1930-e              0                0         0       373     0
       1940-e              0                0         0       419     0
       1950-e              0              495         0       335     0
       1960-e              0              516         0       515     0
       1970-e            524              634         0       517   313
       1980-e            802              962         0       658   564
       1990-e           1413             1346       312       795   711
       2000-e           1019             1803       341      1304  2161
       2010-e           1085             3207       599      1531  1775
       2020-e            997             2064       430      1060  1020
high   1900-e              0                0         0         0     0
       1920-e              0                0         0         0     0
       1930-e            405                0         0         0     0
       1940-e              0                0         0       653   410
       1950-e            768             1063         0      2292   600
       1960-e            520              791         0       763  1185
       1970-e            469             6911         0       478   630
       1980-e           7010             4932         0      1081   458
       1990-e           4558             4015         0      7321   351
       2000-e           4105             5639         0      5210   667
       2010-e           3230             5899       485      3421  7884
       2020-e           1970             4735       603      2335  2253

main_genre           Western
rating release_year
low    1980-e              0
       1990-e              0
       2000-e              0
       2010-e              0
       2020-e              0
medium 1920-e              0
       1930-e              0
       1940-e              0
       1950-e            322
       1960-e            338
       1970-e            534
       1980-e            681
       1990-e            633
       2000-e           1044
       2010-e            651
       2020-e            990
high   1900-e              0
       1920-e              0
       1930-e              0
       1940-e            708
       1950-e            557
       1960-e           1721
       1970-e           1618
       1980-e            807
       1990-e           3122
       2000-e           1007
       2010-e           3450
       2020-e           8624

Транспонировать таблицу (или создать новую другую) с `MultiIndex`

In [148]:
data_multi.T

release_year    1900-e 1920-e       1930-e       1940-e       1950-e        \
rating            high medium  high medium  high medium  high medium  high
main_genre
Action               0      0   936      0     0      0     0      0  3505
Adventure         1706      0  1529      0  1410      0  1716    577   987
Animation            0      0     0      0   513    553  4717    452  5440
Comedy               0      0   929      0   878    353   951    500   889
Crime              584      0     0      0   448    344   674      0   889
Drama                0    504   814      0  1386    312  1132    515   860
Family               0      0     0      0     0      0     0      0  6494
Fantasy              0      0     0      0   326      0  7143      0   542
History              0      0     0      0     0      0     0      0     0
Horror               0      0  1895    583   912      0   729    437     0
Music                0      0     0    375     0      0     0      0   549
Mystery              0      0     0      0     0    554  1642      0   798
Romance              0      0     0      0   405      0     0      0   768
Science Fiction      0      0     0      0     0      0     0    495  1063
TV Movie             0      0     0      0     0      0     0      0     0
Thriller             0      0     0    373     0    419   653    335  2292
War                  0      0     0      0     0      0   410      0   600
Western              0      0     0      0     0      0   708    322   557

release_year    1960-e  ... 1990-e 2000-e              2010-e                \
rating          medium  ...   high    low medium  high    low medium   high
main_genre              ...
Action             559  ...   3059    459   1853  5886      0   2986   6634
Adventure         1395  ...   5067      0   2493  8399      0   2839   8194
Animation            0  ...   2340      0   1315  4083      0   2201   2984
Comedy             501  ...   2299    329   1272  2582    955   1349   3145
Crime              314  ...   3214      0   1065  3045      0   1452   4339
Drama              499  ...   2181      0    925  2675      0   1166   3009
Family               0  ...   5048      0   1814  2364      0   1439   3266
Fantasy           4975  ...   4724      0   2145  5549      0   2906   6431
History              0  ...      0      0    492   382      0   1297   5351
Horror             447  ...   2965    346   1496  4093   1530   1474   3979
Music              652  ...   1143      0    684     0      0   1044   1546
Mystery            301  ...    549      0   1311  4216      0    971  10282
Romance              0  ...   4558      0   1019  4105      0   1085   3230
Science Fiction    516  ...   4015    606   1803  5639      0   3207   5899
TV Movie             0  ...      0      0    341     0      0    599    485
Thriller           515  ...   7321      0   1304  5210      0   1531   3421
War                  0  ...    351      0   2161   667      0   1775   7884
Western            338  ...   3122      0   1044  1007      0    651   3450

release_year    2020-e
rating             low medium  high
main_genre
Action               0   2437  5525
Adventure            0   3296  4825
Animation            0   1159  1984
Comedy             446    986  2446
Crime                0   1441  3190
Drama                0   1014  1985
Family               0   1966  2454
Fantasy              0   2386  3530
History              0    936  1390
Horror            1026   1415  4523
Music                0    406  2608
Mystery              0   1762  3793
Romance              0    997  1970
Science Fiction      0   2064  4735
TV Movie             0    430   603
Thriller             0   1060  2335
War                  0   1020  2253
Western              0    990  8624

[18 rows x 28 columns]

Удалить один из уровней индекса или добавить новый уровень индекса (можно инициализированный константой)

In [152]:
#удалить уровень
data_multi.droplevel('release_year')

main_genre,Action,Adventure,Animation,Comedy,Crime,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
rating,,,,,,,,,,,,,,,,,,
high,0,1706,0,0,584,0,0,0,0,0,0,0,0,0,0,0,0,0
medium,0,0,0,0,0,504,0,0,0,0,0,0,0,0,0,0,0,0
high,936,1529,0,929,0,814,0,0,0,1895,0,0,0,0,0,0,0,0
medium,0,0,0,0,0,0,0,0,0,583,375,0,0,0,0,373,0,0
high,0,1410,513,878,448,1386,0,326,0,912,0,0,405,0,0,0,0,0
medium,0,0,553,353,344,312,0,0,0,0,0,554,0,0,0,419,0,0
high,0,1716,4717,951,674,1132,0,7143,0,729,0,1642,0,0,0,653,410,708
medium,0,577,452,500,0,515,0,0,0,437,0,0,0,495,0,335,0,322
high,3505,987,5440,889,889,860,6494,542,0,0,549,798,768,1063,0,2292,600,557
medium,559,1395,0,501,314,499,0,4975,0,447,652,301,0,516,0,515,0,338
high,1427,2615,1629,1144,966,860,5093,2852,2357,1621,1243,2810,520,791,0,763,1185,1721
medium,890,1222,307,579,516,513,580,419,0,516,435,394,524,634,0,517,313,534
high,1051,918,2727,759,1145,1520,3283,400,1045,2589,646,381,469,6911,0,478,630,1618
low,0,0,0,0,0,0,0,441,0,0,0,0,0,0,0,0,0,0
medium,766,1125,779,635,544,775,518,948,0,802,1842,593,802,962,0,658,564,681
high,2869,6396,638,1600,2454,1655,953,2121,2694,4413,1569,466,7010,4932,0,1081,458,807
low,0,0,0,0,0,0,0,0,0,407,0,0,0,0,0,0,0,0
medium,1052,1432,645,973,849,727,916,890,0,872,1720,421,1413,1346,312,795,711,633
high,3059,5067,2340,2299,3214,2181,5048,4724,0,2965,1143,549,4558,4015,0,7321,351,3122
low,459,0,0,329,0,0,0,0,0,346,0,0,0,606,0,0,0,0
medium,1853,2493,1315,1272,1065,925,1814,2145,492,1496,684,1311,1019,1803,341,1304,2161,1044
high,5886,8399,4083,2582,3045,2675,2364,5549,382,4093,0,4216,4105,5639,0,5210,667,1007
low,0,0,0,955,0,0,0,0,0,1530,0,0,0,0,0,0,0,0
medium,2986,2839,2201,1349,1452,1166,1439,2906,1297,1474,1044,971,1085,3207,599,1531,1775,651
high,6634,8194,2984,3145,4339,3009,3266,6431,5351,3979,1546,10282,3230,5899,485,3421,7884,3450
low,0,0,0,446,0,0,0,0,0,1026,0,0,0,0,0,0,0,0
medium,2437,3296,1159,986,1441,1014,1966,2386,936,1415,406,1762,997,2064,430,1060,1020,990
high,5525,4825,1984,2446,3190,1985,2454,3530,1390,4523,2608,3793,1970,4735,603,2335,2253,8624

**№11.** Продемонстировать работу `.merge`

In [155]:
#Создадим фрейм с данными о популярности каждого жанра
genge_popularity = data['main_genre'].unique()
popularity = np.random.randint(1, 11, genge_popularity.shape)
genge_popularity_frame = pd.DataFrame(
    {
        'main_genre': genge_popularity,
        'genge_popularity': popularity,
    }
)
genge_popularity_frame

         main_genre  genge_popularity
0             Drama                 9
1            Comedy                 7
2         Animation                 7
3           Fantasy                 7
4          Thriller                 7
5         Adventure                 6
6           Western                 2
7            Action                 4
8            Family                 1
9           Romance                 9
10           Horror                 8
11            Music                 5
12            Crime                10
13              War                 1
14         TV Movie                 8
15  Science Fiction                10
16          History                 1
17          Mystery                10

In [156]:
pd.merge(data, genge_popularity_frame, how='left', on='main_genre')

,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names,success,"vote_average, %",is_new,rating,release_year,main_genre,genge_popularity
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221.0,"['Drama', 'Crime']",1010.111,87.05,False,high,1990-e,Drama,9
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877.0,"['Drama', 'Crime']",1459.317,86.95,False,high,1970-e,Drama,9
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001.0,"['Drama', 'Crime']",1414.251,85.76,False,high,1970-e,Drama,9
3,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409.0,"['Drama', 'History', 'War']",659.993,85.67,False,high,1990-e,Drama,9
4,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276.0,['Drama'],653.950,85.41,False,high,1960-e,Drama,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9328,FearDotCom,When four bodies are discovered among the indu...,2002-08-09,14.975,3.724,346.0,"['Horror', 'Thriller', 'Crime']",55.767,37.24,False,low,2000-e,Horror,8
9329,The Open House,A teenager and his mother find themselves besi...,2018-01-19,14.647,3.701,1317.0,"['Horror', 'Thriller']",54.209,37.01,False,low,2020-e,Horror,8
9330,Les Dalton,Joe and Averell are the eldest and youngest of...,2004-11-08,21.351,3.681,329.0,"['Comedy', 'Western', 'Adventure']",78.593,36.81,False,low,2000-e,Comedy,7
9331,The Star Wars Holiday Special,Luke Skywalker and Han Solo battle evil Imperi...,1978-11-17,11.516,3.300,441.0,"['Fantasy', 'Science Fiction', 'Family', 'TV M...",38.003,33.00,False,low,1980-e,Fantasy,7
9332,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,22.800,3.270,814.0,"['Science Fiction', 'Action', 'Adventure']",74.556,32.70,False,low,2000-e,Science Fiction,10

**№12**. Продемонстрировать работу с `.concat` или `.append`

In [171]:
pd.concat([data.iloc[0:5], data.iloc[10:15]])

,original_title,overview,release_date,popularity,vote_average,vote_count,genre_names,success,"vote_average, %",is_new,rating,release_year,main_genre
id,,,,,,,,,,,,,
278.0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,116.038,8.705,26221.0,"['Drama', 'Crime']",1010.111,87.05,False,high,1990-e,Drama
238.0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.834,8.695,19877.0,"['Drama', 'Crime']",1459.317,86.95,False,high,1970-e,Drama
240.0,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,164.908,8.576,12001.0,"['Drama', 'Crime']",1414.251,85.76,False,high,1970-e,Drama
424.0,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,77.039,8.567,15409.0,"['Drama', 'History', 'War']",659.993,85.67,False,high,1990-e,Drama
389.0,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,76.566,8.541,8276.0,['Drama'],653.950,85.41,False,high,1960-e,Drama
372058.0,君の名は。,High schoolers Mitsuha and Taki are complete s...,2016-08-26,71.048,8.495,10986.0,"['Animation', 'Romance', 'Drama']",603.553,84.95,False,high,2020-e,Animation
680.0,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,528.384,8.489,27138.0,"['Thriller', 'Crime']",4485.452,84.89,False,high,1990-e,Thriller
122.0,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-01,125.470,8.480,23439.0,"['Adventure', 'Fantasy', 'Action']",1063.986,84.80,False,high,2000-e,Adventure
13.0,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,177.031,8.475,26660.0,"['Comedy', 'Drama', 'Romance']",1500.338,84.75,False,high,1990-e,Comedy
429.0,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,1966-12-22,71.347,8.467,8285.0,['Western'],604.095,84.67,False,high,1970-e,Western